name: Build, format, and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - run: pnpm build
      - run: pnpm prettier --check .
      - run: pnpm test
