name: Build, format, and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: pnpm/action-setup@v4.1.0

      - uses: actions/setup-node@v4.2.0
        with:
          node-version: 20.x

      - run: pnpm install
      - run: pnpm build
      - run: pnpm lint
      - run: pnpm test
